package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class CzLocalization : Localization {
    override val setupAction: String = "Nainstalovat"
    override val setupDescription: String = "Automatická instalace lokalizačních souborů a záplat"
    override val nextAction: String = "Další"
    override val gameDirectory: String = "Herní adresář"
    override val savesDirectory: String = "Adresář uložených her"
    override val selectDirectory: String = "Vybrat adresář"
    override val fileNotFound: String = "Soubor nenalezen"
    override val installation: String = "Instalace"
    override val file: String = "Soubor"
    override val removingOutdatedFiles: String = "Odstraňování zastaralých souborů"
    override val backupSaves: String = "Zálohování uložených her"
    override val installationError: String = "Chyba instalace"
    override val play: String = "Hrát"
    override val playMods: String = "Hrát (mody)"
    override val options: String = "Nastavení"
    override val language: String = "Jazyk"
    override val graphics: String = "Grafika"
    override val game: String = "Hra"
    override val general: String = "Obecné"
    override val textLanguage: String = "Jazyk textu"
    override val voiceLanguage: String = "Jazyk dabingu"
    override val additional: String = "Další"
    override val subtitles: String = "Titulky"
    override val showSubtitlesInDialogs: String = "Zobrazit titulky v dialozích"
    override val gothicFonts: String = "Gotická písma"
    override val fontDescription: String = "Zaškrtnuto: Písmo Gothic3\nNezaškrtnuto: Písmo Comic Sans MS"
    override val localizedIntro: String = "Lokalizované úvodní video"
    override val introDescription: String = "Zaškrtnuto: Úvodní video s ruským dabingem od Russobit-M\nNezaškrtnuto: Původní úvodní video"
    override val main: String = "Hlavní"
    override val configure: String = "Nastavit"
    override val detailLevel: String = "Úroveň detailů"
    override val verticalSync: String = "Vertikální synchronizace"
    override val fpsLimit60: String = "Omezení na 60 FPS"
    override val default: String = "Výchozí"
    override val low: String = "Nízká"
    override val medium: String = "Střední"
    override val high: String = "Vysoká"
    override val veryHigh: String = "Velmi Vysoká"
    override val custom: String = "Vlastní"
    override val verticalSyncDescription: String = "Synchronizuje snímkovou frekvenci s obnovovací frekvencí obrazovky. Zaškrtnuto: Pokud se vyskytují problémy s trháním obrazu nebo animace je příliš rychlá při vysokém fps. Nezaškrtnuto: Pro zvýšení výkonu"
    override val fpsLimit60Description: String = "Nastaví obnovovací frekvenci obrazovky na 60 fps. Bude aktivována vertikální synchronizace"
    override val drawDistance: String = "Vykreslovací vzdálenost"
    override val additionalLocalizationPackage: String = "Dodatečný lokalizační balíček"
    override val patchesLoading: String = "Načítání záplat"
    override val localizationFilesLoading: String = "Načítání lokalizačních souborů"
    override val patchesInstallation: String = "Instalace záplat"
    override val localizationInstallation: String = "Instalace lokalizace"
    override val patchedGameFilesLoading: String = "Načítání opravených herních souborů"
    override val cleanupObsoleteFiles: String = "Odstraňování zastaralých souborů, odkazů a souborů změn"
    override val archiveReassembly: String = "Všechny části hlavních archivů byly sloučeny. Archivy byly znovu sestaveny"
    override val voiceFilesCopying: String = "Kopírování hlasových souborů do herního adresáře. Angličtina vybrána jako výchozí jazyk"
    override val saveBackup: String = "Zálohování uložení v době instalace"
    override val localizationFilesLoadingNote: String = "Poznámka: Během spuštění hry by měl být aktivní pouze 1 Speech soubor. Při hraní bez spouštěče odstraňte ; před požadovaným hlasovým souborem v Ini/mountlist.ini"
    override val download: String = "Stáhnout"
    override val resume: String = "Pokračovat"
}