package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class DeLocalization : Localization {
    override val setupAction: String = "Installieren"
    override val setupDescription: String = "Automatische Installation von Lokalisierungsdateien und Patches"
    override val nextAction: String = "Weiter"
    override val gameDirectory: String = "Spielverzeichnis"
    override val savesDirectory: String = "Spielstandverzeichnis"
    override val selectDirectory: String = "Verzeichnis auswählen"
    override val fileNotFound: String = "Datei nicht gefunden"
    override val installation: String = "Installation"
    override val file: String = "Datei"
    override val removingOutdatedFiles: String = "Entfernen veralteter Dateien"
    override val backupSaves: String = "Sicherungskopien der Spielstände"
    override val installationError: String = "Installationsfehler"
    override val play: String = "Spielen"
    override val playMods: String = "Spielen (Mods)"
    override val options: String = "Optionen"
    override val language: String = "Sprache"
    override val graphics: String = "Grafik"
    override val game: String = "Spiel"
    override val general: String = "Allgemein"
    override val textLanguage: String = "Textsprache"
    override val voiceLanguage: String = "Sprachausgabe"
    override val additional: String = "Zusätzlich"
    override val subtitles: String = "Untertitel"
    override val showSubtitlesInDialogs: String = "Untertitel in Dialogen anzeigen"
    override val gothicFonts: String = "Gotische Schriftarten"
    override val fontDescription: String = "Aktiviert: Gothic3-Schrift\nDeaktiviert: Comic Sans MS-Schrift"
    override val localizedIntro: String = "Lokalisiertes Intro-Video"
    override val introDescription: String = "Aktiviert: Intro mit russischer Vertonung von Russobit-M\nDeaktiviert: Originales Intro"
    override val main: String = "Haupt"
    override val configure: String = "Konfigurieren"
    override val detailLevel: String = "Detaillierungsgrad"
    override val verticalSync: String = "Vertikale Synchronisation"
    override val fpsLimit60: String = "60 FPS Begrenzung"
    override val default: String = "Standard"
    override val low: String = "Niedrig"
    override val medium: String = "Mittel"
    override val high: String = "Hoch"
    override val veryHigh: String = "Sehr Hoch"
    override val custom: String = "Benutzerdefiniert"
    override val verticalSyncDescription: String = "Synchronisiert die Bildrate mit der Bildwiederholfrequenz des Bildschirms. Aktiviert: Bei Problemen mit Screen Tearing oder zu schneller Animation bei hoher fps. Deaktiviert: Zur Leistungssteigerung"
    override val fpsLimit60Description: String = "Setzt die Bildwiederholfrequenz auf 60 fps. Vertikale Synchronisation wird aktiviert"
    override val drawDistance: String = "Zeichnungsentfernung"
    override val additionalLocalizationPackage: String = "Zusätzliches Lokalisierungspaket"
    override val patchesLoading: String = "Laden von Patches"
    override val localizationFilesLoading: String = "Laden von Lokalisierungsdateien"
    override val patchesInstallation: String = "Installieren von Patches"
    override val localizationInstallation: String = "Installieren der Lokalisierung"
    override val patchedGameFilesLoading: String = "Laden gepatchter Spieledateien"
    override val cleanupObsoleteFiles: String = "Entfernen veralteter Dateien, Links und Änderungsdateien"
    override val archiveReassembly: String = "Alle Hauptarchivteile wurden zusammengeführt. Archive wurden neu erstellt"
    override val voiceFilesCopying: String = "Kopieren von Sprachdateien ins Spielverzeichnis. Standardmäßig ist Englisch ausgewählt"
    override val saveBackup: String = "Sicherung der Spielstände zum Zeitpunkt der Installation"
    override val localizationFilesLoadingNote: String = "Hinweis: Während des Spielstarts sollte nur 1 Speech-Datei aktiv sein. Wenn Sie ohne Launcher spielen, entfernen Sie das ; vor der gewünschten Sprachdatei in Ini/mountlist.ini"
    override val download: String = "Herunterladen"
    override val resume: String = "Fortsetzen"
    override val copyDirectory: String = "Verzeichnis kopieren"
    override val copyCurrentGameDirectory: String = "Kopie des aktuellen Spielverzeichnisses"
    override val playWithMods: String = "Mit Mods spielen"
    override val modCopyDescription: String = "Eine Kopie des Spiels wird zum Spielen mit Mods erstellt.\n\nSpeicherstände des normalen Spiels und des Mod-Spiels werden getrennt.\n\nEs wird empfohlen, das Mod-Spiel nur über den Launcher zu starten, um Speicherstandsverwirrung zu vermeiden"
    override val deleteModDirectory: String = "Mod-Verzeichnis löschen"
    override val deleteModWarning: String = "Achtung! Das Verzeichnis mit allen installierten Mods wird gelöscht.\n\nSpeicherstände werden nicht betroffen"
    override val mainDirectories: String = "Hauptverzeichnisse"
    override val moddedGameDirectory: String = "Mod-Spielverzeichnis"
    override val gameSettingsFiles: String = "Spieleinstellungsdateien"
    override val deleteConfirmation: String = "Löschbestätigung"
    override val deleteModDirectoryConfirmation: String = "Sind Sie sicher, dass Sie das Mod-Verzeichnis löschen möchten?"
    override val failedToDeleteModDirectory: String = "Löschen des Mod-Verzeichnisses fehlgeschlagen:"
    override val error: String = "Fehler"
}