package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class DeLocalization : Localization {
    override val setupAction: String = "Installieren"
    override val setupDescription: String = "Automatische Installation von Lokalisierungsdateien und Patches"
    override val nextAction: String = "Weiter"
    override val gameDirectory: String = "Spielverzeichnis"
    override val savesDirectory: String = "Spielstandverzeichnis"
    override val selectDirectory: String = "Verzeichnis auswählen"
    override val fileNotFound: String = "Datei nicht gefunden"
    override val installation: String = "Installation"
    override val file: String = "Datei"
    override val removingOutdatedFiles: String = "Entfernen veralteter Dateien"
    override val backupSaves: String = "Sicherungskopien der Spielstände"
    override val installationError: String = "Installationsfehler"
    override val play: String = "Spielen"
    override val playMods: String = "Spielen (Mods)"
    override val options: String = "Optionen"
    override val language: String = "Sprache"
    override val graphics: String = "Grafik"
    override val game: String = "Spiel"
    override val general: String = "Allgemein"
    override val textLanguage: String = "Textsprache"
    override val voiceLanguage: String = "Sprachausgabe"
    override val additional: String = "Zusätzlich"
    override val subtitles: String = "Untertitel"
    override val showSubtitlesInDialogs: String = "Untertitel in Dialogen anzeigen"
    override val gothicFonts: String = "Gotische Schriftarten"
    override val fontDescription: String = "Aktiviert: Gothic3-Schrift\nDeaktiviert: Comic Sans MS-Schrift"
    override val localizedIntro: String = "Lokalisiertes Intro-Video"
    override val introDescription: String = "Aktiviert: Intro mit russischer Vertonung von Russobit-M\nDeaktiviert: Originales Intro"
    override val main: String = "Haupt"
    override val configure: String = "Konfigurieren"
    override val detailLevel: String = "Detaillierungsgrad"
    override val verticalSync: String = "Vertikale Synchronisation"
    override val fpsLimit60: String = "60 FPS Begrenzung"
    override val default: String = "Standard"
    override val low: String = "Niedrig"
    override val medium: String = "Mittel"
    override val high: String = "Hoch"
    override val veryHigh: String = "Sehr Hoch"
    override val custom: String = "Benutzerdefiniert"
    override val verticalSyncDescription: String = "Synchronisiert die Bildrate mit der Bildwiederholfrequenz des Bildschirms. Aktiviert: Bei Problemen mit Screen Tearing oder zu schneller Animation bei hoher fps. Deaktiviert: Zur Leistungssteigerung"
    override val fpsLimit60Description: String = "Setzt die Bildwiederholfrequenz auf 60 fps. Vertikale Synchronisation wird aktiviert"
    override val drawDistance: String = "Zeichnungsentfernung"
    override val additionalLocalizationPackage: String = "Zusätzliches Lokalisierungspaket"
}