package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class EnLocalization : Localization {
    override val setupAction: String = "Install"
    override val setupDescription: String = "Automatic installation of localization files and patches"
    override val nextAction: String = "Next"
    override val gameDirectory: String = "Game Directory"
    override val savesDirectory: String = "Saves Directory"
    override val selectDirectory: String = "Select Directory"
    override val fileNotFound: String = "File not found"
    override val installation: String = "Installation"
    override val file: String = "File"
    override val removingOutdatedFiles: String = "Removing outdated files"
    override val backupSaves: String = "Backup saves"
    override val installationError: String = "Installation error"
    override val play: String = "Play"
    override val playMods: String = "Play (mods)"
    override val options: String = "Options"
    override val language: String = "Language"
    override val graphics: String = "Graphics"
    override val game: String = "Game"
    override val general: String = "General"
    override val textLanguage: String = "Text language"
    override val voiceLanguage: String = "Voice language"
    override val additional: String = "Additional"
    override val subtitles: String = "Subtitles"
    override val showSubtitlesInDialogs: String = "Show subtitles in dialogs"
    override val gothicFonts: String = "Gothic fonts"
    override val fontDescription: String = "Checked: Gothic3 font\nUnchecked: Comic Sans MS font"
    override val localizedIntro: String = "Localized intro video"
    override val introDescription: String = "Checked: Intro with Russian voiceover by Russobit-M\nUnchecked: Original intro"
    override val main: String = "Main"
    override val configure: String = "Configure"
    override val detailLevel: String = "Detail level"
    override val verticalSync: String = "Vertical sync"
    override val fpsLimit60: String = "60 FPS limit"
    override val default: String = "Default"
    override val low: String = "Low"
    override val medium: String = "Medium"
    override val high: String = "High"
    override val veryHigh: String = "Very High"
    override val custom: String = "Custom"
    override val verticalSyncDescription: String = "Synchronizes frame rate with screen refresh rate. Checked: If there are issues with screen tearing or animation is too fast at high fps. Unchecked: To increase performance"
    override val fpsLimit60Description: String = "Sets screen refresh rate to 60 fps. Vertical sync will be enabled"
    override val drawDistance: String = "Draw Distance"
    override val additionalLocalizationPackage: String = "Additional localization package"
    override val patchesLoading: String = "Loading patches"
    override val localizationFilesLoading: String = "Loading localization files"
    override val patchesInstallation: String = "Installing patches"
    override val localizationInstallation: String = "Installing localization"
    override val patchedGameFilesLoading: String = "Loading patched game files"
    override val cleanupObsoleteFiles: String = "Removing outdated files, links, and change files"
    override val archiveReassembly: String = "All main archive parts have been merged. Archives have been rebuilt"
    override val voiceFilesCopying: String = "Copying voice files to the game directory. English language selected by default"
    override val saveBackup: String = "Backing up saves at the time of installation"
    override val localizationFilesLoadingNote: String = "Note: During game launch, only 1 Speech file should be active. When playing without a launcher, remove the ; before the desired voice file in Ini/mountlist.ini"
    override val download: String = "Download"
    override val resume: String = "Resume"
}