package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class EsLocalization : Localization {
    override val setupAction: String = "Instalar"
    override val setupDescription: String = "Instalación automática de archivos de localización y parches"
    override val nextAction: String = "Siguiente"
    override val gameDirectory: String = "Directorio del juego"
    override val savesDirectory: String = "Directorio de guardados"
    override val selectDirectory: String = "Seleccionar directorio"
    override val fileNotFound: String = "Archivo no encontrado"
    override val installation: String = "Instalación"
    override val file: String = "Archivo"
    override val removingOutdatedFiles: String = "Eliminando archivos obsoletos"
    override val backupSaves: String = "Respaldar guardados"
    override val installationError: String = "Error de instalación"
    override val play: String = "Jugar"
    override val playMods: String = "Jugar (mods)"
    override val options: String = "Opciones"
    override val language: String = "Idioma"
    override val graphics: String = "Gráficos"
    override val game: String = "Juego"
    override val general: String = "General"
    override val textLanguage: String = "Idioma del texto"
    override val voiceLanguage: String = "Idioma de voces"
    override val additional: String = "Adicional"
    override val subtitles: String = "Subtítulos"
    override val showSubtitlesInDialogs: String = "Mostrar subtítulos en diálogos"
    override val gothicFonts: String = "Fuentes góticas"
    override val fontDescription: String = "Marcado: Fuente Gothic3\nDesmarcado: Fuente Comic Sans MS"
    override val localizedIntro: String = "Video introductorio localizado"
    override val introDescription: String = "Marcado: Intro con doblaje ruso de Russobit-M\nDesmarcado: Intro original"
    override val main: String = "Principal"
    override val configure: String = "Configurar"
    override val detailLevel: String = "Nivel de detalle"
    override val verticalSync: String = "Sincronización vertical"
    override val fpsLimit60: String = "Límite de 60 FPS"
    override val default: String = "Por defecto"
    override val low: String = "Bajo"
    override val medium: String = "Medio"
    override val high: String = "Alto"
    override val veryHigh: String = "Muy Alto"
    override val custom: String = "Personalizado"
    override val verticalSyncDescription: String = "Sincroniza la tasa de fotogramas con la frecuencia de actualización de la pantalla. Marcado: Si hay problemas con tearing o la animación es demasiado rápida a alto fps. Desmarcado: Para aumentar el rendimiento"
    override val fpsLimit60Description: String = "Establece la frecuencia de actualización de la pantalla a 60 fps. Se activará la sincronización vertical"
    override val drawDistance: String = "Distancia de dibujado"
    override val additionalLocalizationPackage: String = "Paquete de localización adicional"
    override val patchesLoading: String = "Cargando parches"
    override val localizationFilesLoading: String = "Cargando archivos de localización"
    override val patchesInstallation: String = "Instalando parches"
    override val localizationInstallation: String = "Instalando localización"
    override val patchedGameFilesLoading: String = "Cargando archivos de juego parcheados"
    override val cleanupObsoleteFiles: String = "Eliminando archivos obsoletos, enlaces y archivos de cambios"
    override val archiveReassembly: String = "Todas las partes de los archivos principales han sido fusionadas. Los archivos han sido reconstruidos"
    override val voiceFilesCopying: String = "Copiando archivos de voz al directorio del juego. Idioma inglés seleccionado por defecto"
    override val saveBackup: String = "Haciendo copia de seguridad de las partidas guardadas en el momento de la instalación"
    override val localizationFilesLoadingNote: String = "Nota: Durante el inicio del juego, solo debe estar activo 1 archivo Speech. Al jugar sin lanzador, elimine el ; antes del archivo de voz deseado en Ini/mountlist.ini"
    override val download: String = "Descargar"
    override val resume: String = "Reanudar"
}