package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class FrLocalization : Localization {
    override val setupAction: String = "Installer"
    override val setupDescription: String = "Installation automatique des fichiers de localisation et correctifs"
    override val nextAction: String = "Suivant"
    override val gameDirectory: String = "Répertoire du jeu"
    override val savesDirectory: String = "Répertoire des sauvegardes"
    override val selectDirectory: String = "Sélectionner le répertoire"
    override val fileNotFound: String = "Fichier non trouvé"
    override val installation: String = "Installation"
    override val file: String = "Fichier"
    override val removingOutdatedFiles: String = "Suppression des fichiers obsolètes"
    override val backupSaves: String = "Sauvegarde des sauvegardes"
    override val installationError: String = "Erreur d'installation"
    override val play: String = "Jouer"
    override val playMods: String = "Jouer (mods)"
    override val options: String = "Options"
    override val language: String = "Langue"
    override val graphics: String = "Graphisme"
    override val game: String = "Jeu"
    override val general: String = "Général"
    override val textLanguage: String = "Langue du texte"
    override val voiceLanguage: String = "Langue des voix"
    override val additional: String = "Supplémentaire"
    override val subtitles: String = "Sous-titres"
    override val showSubtitlesInDialogs: String = "Afficher les sous-titres dans les dialogues"
    override val gothicFonts: String = "Polices gothiques"
    override val fontDescription: String = "Coché: Police Gothic3\nDéscoché: Police Comic Sans MS"
    override val localizedIntro: String = "Vidéo d'introduction localisée"
    override val introDescription: String = "Coché: Introduction avec doublage russe par Russobit-M\nDéscoché: Introduction originale"
    override val main: String = "Principal"
    override val configure: String = "Configurer"
    override val detailLevel: String = "Niveau de détail"
    override val verticalSync: String = "Synchronisation verticale"
    override val fpsLimit60: String = "Limite à 60 FPS"
    override val default: String = "Par défaut"
    override val low: String = "Faible"
    override val medium: String = "Moyen"
    override val high: String = "Élevé"
    override val veryHigh: String = "Très Élevé"
    override val custom: String = "Personnalisé"
    override val verticalSyncDescription: String = "Synchronise le taux de rafraîchissement avec la fréquence d'actualisation de l'écran. Coché: En cas de déchirement d'écran ou d'animation trop rapide à haut fps. Décoché: Pour augmenter les performances"
    override val fpsLimit60Description: String = "Définit la fréquence de rafraîchissement de l'écran à 60 fps. La synchronisation verticale sera activée"
    override val drawDistance: String = "Distance d'affichage"
    override val additionalLocalizationPackage: String = "Forfait de localisation supplémentaire"
    override val patchesLoading: String = "Chargement des patches"
    override val localizationFilesLoading: String = "Chargement des fichiers de localisation"
    override val patchesInstallation: String = "Installation des patches"
    override val localizationInstallation: String = "Installation de la localisation"
    override val patchedGameFilesLoading: String = "Chargement des fichiers de jeu patchés"
    override val cleanupObsoleteFiles: String = "Suppression des fichiers obsolètes, des liens et des fichiers de modifications"
    override val archiveReassembly: String = "Toutes les parties des archives principales ont été fusionnées. Les archives ont été reconstruites"
    override val voiceFilesCopying: String = "Copie des fichiers vocaux dans le répertoire du jeu. Langue anglaise sélectionnée par défaut"
    override val saveBackup: String = "Sauvegarde des sauvegardes au moment de l'installation"
    override val localizationFilesLoadingNote: String = "Remarque : lors du lancement du jeu, seul 1 fichier Speech doit être actif. Lorsque vous jouez sans lanceur, supprimez le ; avant le fichier vocal souhaité dans Ini/mountlist.ini"
    override val download: String = "Télécharger"
    override val resume: String = "Reprendre"
}