package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class HuLocalization : Localization {
    override val setupAction: String = "Telepítés"
    override val setupDescription: String = "A lokalizációs fájlok és patch-ek automatikus telepítése"
    override val nextAction: String = "Tovább"
    override val gameDirectory: String = "Játék könyvtár"
    override val savesDirectory: String = "Mentések könyvtára"
    override val selectDirectory: String = "Könyvtár kiválasztása"
    override val fileNotFound: String = "Fájl nem található"
    override val installation: String = "Telepítés"
    override val file: String = "Fájl"
    override val removingOutdatedFiles: String = "Elavult fájlok eltávolítása"
    override val backupSaves: String = "Mentések biztonsági mentése"
    override val installationError: String = "Telepítési hiba"
    override val play: String = "Játék"
    override val playMods: String = "Játék (modok)"
    override val options: String = "Beállítások"
    override val language: String = "Nyelv"
    override val graphics: String = "Grafika"
    override val game: String = "Játék"
    override val general: String = "Általános"
    override val textLanguage: String = "Szöveg nyelv"
    override val voiceLanguage: String = "Hang nyelv"
    override val additional: String = "További"
    override val subtitles: String = "Feliratok"
    override val showSubtitlesInDialogs: String = "Feliratok megjelenítése párbeszédekben"
    override val gothicFonts: String = "Gótikus betűtípusok"
    override val fontDescription: String = "Bejelölve: Gothic3 betűtípus\nNincs bejelölve: Comic Sans MS betűtípus"
    override val localizedIntro: String = "Honosított bevezető videó"
    override val introDescription: String = "Bejelölve: Bevezető orosz szinkronnal a Russobit-M-től\nNincs bejelölve: Eredeti bevezető"
    override val main: String = "Fő"
    override val configure: String = "Beállítás"
    override val detailLevel: String = "Részletesség szintje"
    override val verticalSync: String = "Függőleges szinkronizálás"
    override val fpsLimit60: String = "60 FPS korlát"
    override val default: String = "Alapértelmezett"
    override val low: String = "Alacsony"
    override val medium: String = "Közepes"
    override val high: String = "Magas"
    override val veryHigh: String = "Nagyon Magas"
    override val custom: String = "Egyéni"
    override val verticalSyncDescription: String = "Szinkronizálja a képkocka sebességet a képfrissítési frekvenciával. Bejelölve: Ha problémák adódnak képszakadással vagy a animáció túl gyors magas fps-nél. Nincs bejelölve: Teljesítmény növeléséhez"
    override val fpsLimit60Description: String = "Beállítja a képfrissítési frekvenciát 60 fps-re. A függőleges szinkronizálás bekapcsol"
    override val drawDistance: String = "Rajzolási távolság"
    override val additionalLocalizationPackage: String = "További lokalizációs csomag"
    override val patchesLoading: String = "Javítások betöltése"
    override val localizationFilesLoading: String = "Honosítási fájlok betöltése"
    override val patchesInstallation: String = "Javítások telepítése"
    override val localizationInstallation: String = "Honosítás telepítése"
    override val patchedGameFilesLoading: String = "Javított játékfájlok betöltése"
    override val cleanupObsoleteFiles: String = "Elavult fájlok, hivatkozások és változtatási fájlok eltávolítása"
    override val archiveReassembly: String = "Az összes fő archívumrész egyesítve lett. Az archívumok újra lettek építve"
    override val voiceFilesCopying: String = "Hangfájlok másolása a játék könyvtárába. Alapértelmezés szerint az angol nyelv van kiválasztva"
    override val saveBackup: String = "Mentések biztonsági mentése a telepítés időpontjában"
    override val localizationFilesLoadingNote: String = "Megjegyzés: A játék indítása során csak 1 Speech fájlnak kell aktívnak lennie. Ha indító nélkül játszik, távolítsa el a ; jelet a kívánt hangfájl előtt az Ini/mountlist.ini fájlban"
    override val download: String = "Letöltés"
    override val resume: String = "Folytatás"

}