package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class ItLocalization : Localization {
    override val setupAction: String = "Installa"
    override val setupDescription: String = "Installazione automatica dei file di localizzazione e delle patch"
    override val nextAction: String = "Avanti"
    override val gameDirectory: String = "Directory di gioco"
    override val savesDirectory: String = "Directory dei salvataggi"
    override val selectDirectory: String = "Seleziona directory"
    override val fileNotFound: String = "File non trovato"
    override val installation: String = "Installazione"
    override val file: String = "File"
    override val removingOutdatedFiles: String = "Rimozione file obsoleti"
    override val backupSaves: String = "Backup salvataggi"
    override val installationError: String = "Errore di installazione"
    override val play: String = "Gioca"
    override val playMods: String = "Gioca (mod)"
    override val options: String = "Opzioni"
    override val language: String = "Lingua"
    override val graphics: String = "Grafica"
    override val game: String = "Gioco"
    override val general: String = "Generale"
    override val textLanguage: String = "Lingua del testo"
    override val voiceLanguage: String = "Lingua dell'audio"
    override val additional: String = "Aggiuntivo"
    override val subtitles: String = "Sottotitoli"
    override val showSubtitlesInDialogs: String = "Mostra sottotitoli nei dialoghi"
    override val gothicFonts: String = "Caratteri gotici"
    override val fontDescription: String = "Selezionato: Carattere Gothic3\nDeselezionato: Carattere Comic Sans MS"
    override val localizedIntro: String = "Video introduttivo localizzato"
    override val introDescription: String = "Selezionato: Intro con doppiaggio russo di Russobit-M\nDeselezionato: Intro originale"
    override val main: String = "Principale"
    override val configure: String = "Configura"
    override val detailLevel: String = "Livello di dettaglio"
    override val verticalSync: String = "Sincronizzazione verticale"
    override val fpsLimit60: String = "Limite a 60 FPS"
    override val default: String = "Predefinito"
    override val low: String = "Basso"
    override val medium: String = "Medio"
    override val high: String = "Alto"
    override val veryHigh: String = "Molto Alto"
    override val custom: String = "Personalizzato"
    override val verticalSyncDescription: String = "Sincronizza il frame rate con la frequenza di aggiornamento dello schermo. Selezionato: Se ci sono problemi con lo screen tearing o l'animazione è troppo veloce ad alto fps. Deselezionato: Per aumentare le prestazioni"
    override val fpsLimit60Description: String = "Imposta la frequenza di aggiornamento dello schermo a 60 fps. La sincronizzazione verticale sarà attivata"
    override val drawDistance: String = "Distanza di visualizzazione"
    override val additionalLocalizationPackage: String = "Pacchetto di localizzazione aggiuntivo"
    override val patchesLoading: String = "Caricamento patch"
    override val localizationFilesLoading: String = "Caricamento file di localizzazione"
    override val patchesInstallation: String = "Installazione patch"
    override val localizationInstallation: String = "Installazione localizzazione"
    override val patchedGameFilesLoading: String = "Caricamento file di gioco patchati"
    override val cleanupObsoleteFiles: String = "Rimozione file obsoleti, collegamenti e file di modifica"
    override val archiveReassembly: String = "Tutte le parti degli archivi principali sono state unite. Gli archivi sono stati ricostruiti"
    override val voiceFilesCopying: String = "Copia dei file vocali nella directory del gioco. Lingua inglese selezionata per impostazione predefinita"
    override val saveBackup: String = "Backup dei salvataggi al momento dell'installazione"
    override val localizationFilesLoadingNote: String = "Nota: durante l'avvio del gioco, deve essere attivo solo 1 file Speech. Quando si gioca senza launcher, rimuovere il ; prima del file vocale desiderato in Ini/mountlist.ini"
    override val download: String = "Scarica"
    override val resume: String = "Riprendi"
    override val copyDirectory: String = "Copia directory"
    override val copyCurrentGameDirectory: String = "Copia della directory corrente del gioco"
    override val playWithMods: String = "Gioca con le mod"
    override val modCopyDescription: String = "Verrà creata una copia del gioco per giocare con le mod.\n\nI salvataggi del gioco normale e di quello con le mod saranno separati.\n\nSi consiglia di avviare il gioco con le mod solo tramite il launcher per evitare confusione con i salvataggi"
    override val deleteModDirectory: String = "Elimina directory delle mod"
    override val deleteModWarning: String = "Attenzione! Verrà eliminata la directory con tutte le mod installate.\n\nI salvataggi non saranno interessati"
    override val mainDirectories: String = "Directory principali"
    override val moddedGameDirectory: String = "Directory del gioco con mod"
    override val gameSettingsFiles: String = "File impostazioni del gioco"
    override val deleteConfirmation: String = "Conferma eliminazione"
    override val deleteModDirectoryConfirmation: String = "Sei sicuro di voler eliminare la directory delle mod?"
    override val failedToDeleteModDirectory: String = "Impossibile eliminare la directory delle mod:"
    override val error: String = "Errore"
}