package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class PlLocalization : Localization {
    override val setupAction: String = "Zainstaluj"
    override val setupDescription: String = "Automatyczna instalacja plików lokalizacji i łat"
    override val nextAction: String = "Dalej"
    override val gameDirectory: String = "Katalog gry"
    override val savesDirectory: String = "Katalog zapisów"
    override val selectDirectory: String = "Wybierz katalog"
    override val fileNotFound: String = "Plik nie znaleziony"
    override val installation: String = "Instalacja"
    override val file: String = "Plik"
    override val removingOutdatedFiles: String = "Usuwanie przestarzałych plików"
    override val backupSaves: String = "Kopia zapasowa zapisów"
    override val installationError: String = "Błąd instalacji"
    override val play: String = "Graj"
    override val playMods: String = "Graj (mody)"
    override val options: String = "Opcje"
    override val language: String = "Język"
    override val graphics: String = "Grafika"
    override val game: String = "Gra"
    override val general: String = "Ogólne"
    override val textLanguage: String = "Język tekstu"
    override val voiceLanguage: String = "Język głosu"
    override val additional: String = "Dodatkowe"
    override val subtitles: String = "Napisy"
    override val showSubtitlesInDialogs: String = "Wyświetlaj napisy w dialogach"
    override val gothicFonts: String = "Gotyczne czcionki"
    override val fontDescription: String = "Zaznaczone: Czcionka Gothic3\nNiezaznaczone: Czcionka Comic Sans MS"
    override val localizedIntro: String = "Zlokalizowany film wprowadzający"
    override val introDescription: String = "Zaznaczone: Intro z rosyjskim dubbingiem od Russobit-M\nNiezaznaczone: Oryginalne intro"
    override val main: String = "Główne"
    override val configure: String = "Skonfiguruj"
    override val detailLevel: String = "Poziom szczegółów"
    override val verticalSync: String = "Synchronizacja pionowa"
    override val fpsLimit60: String = "Ograniczenie do 60 FPS"
    override val default: String = "Domyślne"
    override val low: String = "Niska"
    override val medium: String = "Średnia"
    override val high: String = "Wysoka"
    override val veryHigh: String = "Bardzo Wysoka"
    override val custom: String = "Niestandardowa"
    override val verticalSyncDescription: String = "Synchronizuje liczbę klatek z częstotliwością odświeżania ekranu. Zaznaczone: W przypadku problemów z rozrywaniem obrazu lub zbyt szybką animacją przy wysokim fps. Niezaznaczone: Aby zwiększyć wydajność"
    override val fpsLimit60Description: String = "Ustawia częstotliwość odświeżania ekranu na 60 fps. Synchronizacja pionowa zostanie włączona"
    override val drawDistance: String = "Zasięg rysowania"
    override val additionalLocalizationPackage: String = "Dodatkowy pakiet lokalizacji"
    override val patchesLoading: String = "Ładowanie łatek"
    override val localizationFilesLoading: String = "Ładowanie plików lokalizacji"
    override val patchesInstallation: String = "Instalowanie łatek"
    override val localizationInstallation: String = "Instalowanie lokalizacji"
    override val patchedGameFilesLoading: String = "Ładowanie załatanych plików gry"
    override val cleanupObsoleteFiles: String = "Usuwanie przestarzałych plików, linków i plików zmian"
    override val archiveReassembly: String = "Wszystkie części głównych archiwów zostały połączone. Archiwa zostały odbudowane"
    override val voiceFilesCopying: String = "Kopiowanie plików głosowych do katalogu gry. Domyślnie wybrany język angielski"
    override val saveBackup: String = "Tworzenie kopii zapasowej zapisów w momencie instalacji"
    override val localizationFilesLoadingNote: String = "Uwaga: Podczas uruchamiania gry aktywny powinien być tylko 1 plik Speech. Podczas gry bez launchera usuń ; przed żądanym plikiem głosowym w pliku Ini/mountlist.ini"
    override val download: String = "Pobierz"
    override val resume: String = "Wznów"
    override val copyDirectory: String = "Kopiowanie katalogu"
    override val copyCurrentGameDirectory: String = "Kopia bieżącego katalogu z grą"
    override val playWithMods: String = "Grać z modami"
    override val modCopyDescription: String = "Zostanie utworzona kopia gry do gry z modami.\n\nZapisy zwykłej gry i gry z modami będą oddzielone.\n\nZaleca się uruchamianie gry z modami tylko przez launcher, aby uniknąć zamieszania z zapisami"
    override val deleteModDirectory: String = "Usuń katalog z modami"
    override val deleteModWarning: String = "Uwaga! Katalog ze wszystkimi zainstalowanymi modami zostanie usunięty.\n\nZapisy nie zostaną naruszone"
    override val mainDirectories: String = "Główne katalogi"
    override val moddedGameDirectory: String = "Katalog gry z modami"
    override val gameSettingsFiles: String = "Pliki ustawień gry"
    override val deleteConfirmation: String = "Potwierdzenie usunięcia"
    override val deleteModDirectoryConfirmation: String = "Czy na pewno chcesz usunąć katalog z modami?"
    override val failedToDeleteModDirectory: String = "Nie udało się usunąć katalogu z modami:"
    override val error: String = "Błąd"
}