package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class RuLocalization : Localization {
    override val setupAction: String = "Установить"
    override val setupDescription: String = "Автоматическая установка файлов локализации и патчей"
    override val nextAction: String = "Далее"
    override val gameDirectory: String = "Директория с игрой"
    override val savesDirectory: String = "Директория с сохранениями"
    override val selectDirectory: String = "Выберите директорию"
    override val fileNotFound: String = "Не найден файл"
    override val installation: String = "Установка"
    override val file: String = "Файл"
    override val removingOutdatedFiles: String = "Удаление устаревших файлов"
    override val backupSaves: String = "Бекап сохранений"
    override val installationError: String = "Ошибка установки"
    override val play: String = "Играть"
    override val playMods: String = "Играть (моды)"
    override val options: String = "Настройки"
    override val language: String = "Язык"
    override val graphics: String = "Графика"
    override val game: String = "Игра"
    override val general: String = "Общее"
    override val textLanguage: String = "Язык текста"
    override val voiceLanguage: String = "Язык озвучивания"
    override val additional: String = "Дополнительно"
    override val subtitles: String = "Субтитры"
    override val showSubtitlesInDialogs: String = "Отображать субтитры в диалогах"
    override val gothicFonts: String = "Готические шрифты"
    override val fontDescription: String = "Checked: Шрифт Gothic3\nUnchecked: Шрифт Comic Sans MS"
    override val localizedIntro: String = "Локализированный стартовый ролик"
    override val introDescription: String = "Checked: Стартовый ролик с озвучкой от Руссобит-М\nUnchecked: Оригинальный ролик"
    override val main: String = "Основное"
    override val configure: String = "Настроить"
    override val detailLevel: String = "Уровень детализации"
    override val verticalSync: String = "Вертикальная синхронизация"
    override val fpsLimit60: String = "Ограничение в 60 FPS"
    override val default: String = "По-умолчанию"
    override val low: String = "Низкая"
    override val medium: String = "Средняя"
    override val high: String = "Высокая"
    override val veryHigh: String = "Очень высокая"
    override val custom: String = "Настроить"
    override val verticalSyncDescription: String = "Синхронизация частоты кадров с частотой развертки экрана. Checked: Если есть проблемы с разрывами изображения или анимации слишком быстрые при высоком fps. Unchecked: Чтобы поднять производительность"
    override val fpsLimit60Description: String = "Установка частоты обновления экрана в 60 fps. Будет включена вертикальная синхронизация"
    override val drawDistance: String = "Дальность прорисовки"
    override val additionalLocalizationPackage: String = "Дополнительный пакет локализации"
}