package com.g3.launcher.localization

import androidx.compose.runtime.Immutable

@Immutable
class TrcLocalization : Localization {
    override val setupAction: String = "安裝"
    override val setupDescription: String = "自動安裝在地化檔案和修補檔"
    override val nextAction: String = "下一步"
    override val gameDirectory: String = "遊戲目錄"
    override val savesDirectory: String = "存檔目錄"
    override val selectDirectory: String = "選擇目錄"
    override val fileNotFound: String = "找不到檔案"
    override val installation: String = "安裝"
    override val file: String = "檔案"
    override val removingOutdatedFiles: String = "刪除過時檔案"
    override val backupSaves: String = "備份存檔"
    override val installationError: String = "安裝錯誤"
    override val play: String = "遊玩"
    override val playMods: String = "遊玩 (模組)"
    override val options: String = "設定"
    override val language: String = "語言"
    override val graphics: String = "圖形"
    override val game: String = "遊戲"
    override val general: String = "一般"
    override val textLanguage: String = "文字語言"
    override val voiceLanguage: String = "語音語言"
    override val additional: String = "附加"
    override val gothicFonts: String = "哥特字體"
    override val fontDescription: String = "已勾選: Gothic3字體\n未勾選: Comic Sans MS字體"
    override val subtitles: String = "字幕"
    override val showSubtitlesInDialogs: String = "在對話中顯示字幕"
    override val localizedIntro: String = "本地化開場影片"
    override val introDescription: String = "已勾選: Russobit-M 俄語配音開場影片\n未勾選: 原始開場影片"
    override val main: String = "主要"
    override val configure: String = "設定"
    override val detailLevel: String = "細節等級"
    override val verticalSync: String = "垂直同步"
    override val fpsLimit60: String = "60 FPS 限制"
    override val default: String = "預設"
    override val low: String = "低"
    override val medium: String = "中"
    override val high: String = "高"
    override val veryHigh: String = "非常高"
    override val custom: String = "自訂"
    override val verticalSyncDescription: String = "將幀率與螢幕刷新率同步。已勾選：如果出現畫面撕裂問題或高幀率下動畫過快。未勾選：以提高效能"
    override val fpsLimit60Description: String = "將螢幕刷新率設定為 60 fps。垂直同步將被啟用"
    override val drawDistance: String = "繪製距離"
    override val additionalLocalizationPackage: String = "附加本地化包"
    override val patchesLoading: String = "加載補丁"
    override val localizationFilesLoading: String = "加載本地化文件"
    override val patchesInstallation: String = "安裝補丁"
    override val localizationInstallation: String = "安裝本地化"
    override val patchedGameFilesLoading: String = "加載已修補的遊戲文件"
    override val cleanupObsoleteFiles: String = "刪除過時的文件、鏈接和更改文件"
    override val archiveReassembly: String = "所有主要存檔部分已合併。存檔已重新構建"
    override val voiceFilesCopying: String = "將語音文件複製到遊戲目錄。默認選擇英語"
    override val saveBackup: String = "安裝時備份保存"
    override val localizationFilesLoadingNote: String = "注意：遊戲啟動期間，只能有1個Speech文件處於活動狀態。不使用啟動器玩遊戲時，請刪除Ini/mountlist.ini中所需語音文件前的;"
    override val download: String = "下載"
    override val resume: String = "繼續"
}